services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_USER=kupidon
      - POSTGRES_PASSWORD=kupidon
      - POSTGRES_DB=kupidon
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/