services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_ROOT_PASSWORD=root
      - POSTGRES_USER=kupidon
      - POSTGRES_PASSWORD=kupidon
      - POSTGRES_DB=kupidon
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_ENV: ${API_ENV}
        API_SECRET_KEY: ${API_SECRET_KEY}
        API_DOMAIN: ${API_DOMAIN}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
    container_name: api
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - API_ENV=${API_ENV}
      - API_DOMAIN=${API_DOMAIN}
    ports:
      - 80:80
    restart: always